export interface IFormDataType {
    tipopessoa: string,
    cnpj: string,
    nome: string,
    ie: string,
    im: string,
    simples: string,
    cep: string,
    pais: string,
    endereco: string,
    estado: string,
    cidade: string,
    bairro: string,
    numero: string,
    complemento: string,
    email: string,
    telefone: string,
    celular: string,
}
